services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: conduitdb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopassword
    ports:
      - 5432:5432
    expose:
      - 5432          
    networks:
      - local_net
    restart: unless-stopped
  
  typesense:
    image: typesense/typesense:0.24.1
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
