services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: conduitdb
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopassword
    ports:
      - 5432:5432
    expose:
      - 5432          
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
